### ISSUE TITLE
HelloIndigo creation not possible, shaders not defined

### ISSUE THREAD

**Issue by ChuuniMage** [PurpleKingdomGames/hello-indigo#2]
I am trying to follow the "HelloIndigo" tutorial https://indigoengine.io/docs/quickstart/hello-indigo here, after following the previous page's setup instructions, and it is telling me the following:

```
[error] -- Error: C:\Users\krisd\Documents\Programming\Scala\indigotest\src\main\scala\Main.scala:5:7 
[error] 5 |object HelloIndigo extends IndigoSandbox[Unit, Unit] {
[error]   |       ^
[error]   |object creation impossible, since val shaders: Set[indigo.Shader] in trait IndigoSandbox in package indigo is not defined
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 5 s, completed 28 May 2021, 6:07:01 pm
```

Have I done something wrong with following the setup, or is this issue correct?

I am using Scala 3 in VS Code with Metals

**Comment by davesmith00000** [comment]
Hi @ChuuniMage, thanks for reporting this. The site docs are out of date I'm afraid (it's on my list of things to do...). I've just pushed a correction but essentially it should look like this:

```scala
  val fonts: Set[FontInfo] =
    Set()

  val shaders: Set[Shader] =
    Set()
```

Please let me know if you find any other problems with the docs, but also if you get stuck, this is the working code for reference:

https://github.com/PurpleKingdomGames/hello-indigo/blob/master/helloindigo/src/HelloIndigo.scala

**Comment by davesmith00000** [comment]
Closing the issue, but please let me know if you have any more trouble. You could always say hello on Discord or Gitter too. :-)
